# название
name: Project build

# целевые события для запуска
# в данном случае это push и pull_request, в ветку master
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# выполняемые действия
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    # запускаются по шагам
    # name - название шага
    # в github actions будет выводиться название шага, и процессы
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - uses: actions/setup-node@v4
        with:
          node-version: 22.17.1

      - name: Install 🔧
        run: npm install
        
      - name: Install Gridsome 🔧
        run: |
          sudo npm uninstall --global @gridsome/cli
          sudo npm install --global @gridsome/cli

      - name: Build 👷
        run: gridsome build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          # в значение GITHUB_TOKEN помещается ссылка на ваш секрет в репозитории
          # в данном случае его название KEY
          GITHUB_TOKEN: ${{ secrets.ACTIONS }}
          BRANCH: gh-pages
          FOLDER: dist
          CLEAN: true
